#CREATE DATABASE portal_comunica;

#USE portal_comunica;

#DROPANDO TODAS AS FKS PARA EXCLUIR AS TABELAS
ALTER TABLE bd_comunic.USUARIO DROP FOREIGN KEY FK_EMPRESA_USUARIO;
ALTER TABLE bd_comunic.GRUPO DROP FOREIGN KEY FK_EMPRESA_GRUPO;
ALTER TABLE bd_comunic.GRUPO_USUARIO DROP FOREIGN KEY FK_GRUPO_GRUPO_USUARIO;
ALTER TABLE bd_comunic.CHAMADO DROP FOREIGN KEY FK_EMPRESA_CHAMADO;
ALTER TABLE bd_comunic.CHAMADO DROP FOREIGN KEY FK_GRUPO_CHAMADO;
ALTER TABLE bd_comunic.ITCHAMADO DROP FOREIGN KEY FK_CHAMADO_ITCHAMADO;

DROP TABLE bd_comunic.EMPRESA;
CREATE TABLE bd_comunic.EMPRESA(
	CD_EMPRESA INT PRIMARY KEY AUTO_INCREMENT,
    DS_EMPRESA VARCHAR(30) NOT NULL,
	CD_USUARIO_CADASTRO INT NOT NULL,
    HR_CADASTRO TIMESTAMP NOT NULL,
    CD_USUARIO_ULT_ALT INT,
    HR_ULT_ALT DATETIME
    
);

DROP TABLE bd_comunic.USUARIO;
CREATE TABLE bd_comunic.USUARIO(
	CD_USUARIO INT PRIMARY KEY AUTO_INCREMENT,
    NM_USUARIO VARCHAR(80) NOT NULL,
    DT_NASCIMENTO DATE NOT NULL,
    EMAIL VARCHAR(80) NOT NULL,
    FOTO VARCHAR(200) NULL,
    CD_EMPRESA INT NOT NULL, #FK DA TABELA EMPRESA
    TP_USUARIO VARCHAR(1) NOT NULL,
    CPF VARCHAR(11) NOT NULL,
    SENHA VARCHAR(30) NOT NULL,
    CD_USUARIO_CADASTRO INT NOT NULL,
    HR_CADASTRO TIMESTAMP NOT NULL,
    CD_USUARIO_ULT_ALT INT NULL,
    HR_ULT_ALT DATETIME,
    
    CONSTRAINT FK_EMPRESA_USUARIO FOREIGN KEY (CD_EMPRESA) REFERENCES bd_comunic.EMPRESA (CD_EMPRESA)
);

DROP TABLE bd_comunic.GRUPO;
CREATE TABLE bd_comunic.GRUPO(
	CD_GRUPO INT PRIMARY KEY AUTO_INCREMENT,
    DS_GRUPO VARCHAR(30) NOT NULL,
    CD_EMPRESA INT NOT NULL, #FK DA TABELA EMPRESA
    CD_USUARIO_CADASTRO INT NOT NULL,
    HR_CADASTRO TIMESTAMP NOT NULL,
    CD_USUARIO_ULT_ALT INT NULL,
    HR_ULT_ALT DATETIME NULL,
    
    CONSTRAINT FK_EMPRESA_GRUPO FOREIGN KEY (CD_EMPRESA) REFERENCES bd_comunic.EMPRESA (CD_EMPRESA)
);

DROP TABLE bd_comunic.GRUPO_USUARIO;
CREATE TABLE bd_comunic.GRUPO_USUARIO(
	CD_GRUPO_USUARIO INT PRIMARY KEY AUTO_INCREMENT,
    CD_GRUPO INT NOT NULL, #FK TABELA GRUPO
    CD_USUARIO INT NOT NULL,
    CD_USUARIO_CADASTRO INT NOT NULL,
    HR_CADASTRO TIMESTAMP NOT NULL,
    CD_USUARIO_ULT_ALT VARCHAR(20) NULL,
    HR_ULT_ALT DATETIME NULL,
    
    CONSTRAINT FK_GRUPO_GRUPO_USUARIO FOREIGN KEY (CD_GRUPO) REFERENCES bd_comunic.GRUPO (CD_GRUPO)
);

DROP TABLE bd_comunic.CHAMADO;
CREATE TABLE bd_comunic.CHAMADO(
	CD_CHAMADO INT PRIMARY KEY AUTO_INCREMENT,
    DS_CHAMADO VARCHAR(80) NOT NULL,
    CD_EMPRESA INT NOT NULL, #FK DA TABELA EMPRESA
    CD_GRUPO INT NOT NULL, #FK DA TEBELA GRUPO
    TP_PRIORIDADE VARCHAR(1) NOT NULL,
    DT_PREVISTA DATE NOT NULL,
    TP_STATUS VARCHAR(1) NOT NULL,
    OBS_MENSAGEM BLOB NULL,
    ANEXO VARCHAR(200) NULL,
    EXT VARCHAR(5) NULL,
    CD_USUARIO_RESPONSAVEL INT NULL,
    HR_RESPONSAVEL INT NULL,
    CD_USUARIO_CADASTRO INT NOT NULL,
    HR_CADASTRO DATETIME NOT NULL,
    CD_USUARIO_ULT_ALT INT NULL,
    HR_ULT_ALT DATETIME NULL,
    
	CONSTRAINT FK_EMPRESA_CHAMADO FOREIGN KEY (CD_EMPRESA) REFERENCES bd_comunic.EMPRESA (CD_EMPRESA),
    CONSTRAINT FK_GRUPO_CHAMADO FOREIGN KEY (CD_GRUPO) REFERENCES bd_comunic.GRUPO (CD_GRUPO)
);

DROP TABLE bd_comunic.ITCHAMADO;
CREATE TABLE bd_comunic.ITCHAMADO(
	CD_ITCHAMADO INT PRIMARY KEY AUTO_INCREMENT,
    CD_CHAMADO INT, #FK DA TABELA CHAMADO
    DS_MENSAGEM BLOB NOT NULL,
    ANEXO VARCHAR(200) NULL,
    EXT VARCHAR(5) NULL,
    CD_USUARIO_CADASTRO INT NOT NULL, #FK DA TABELA CHAMADO
    HR_CADASTRO DATETIME NOT NULL,
    CD_USUARIO_ULT_ALT VARCHAR(20) NULL,
    HR_ULT_ALT DATETIME NULL,
    
    CONSTRAINT FK_CHAMADO_ITCHAMADO FOREIGN KEY (CD_CHAMADO) REFERENCES bd_comunic.CHAMADO (CD_CHAMADO)
);

SELECT * FROM bd_comunic.EMPRESA;
SELECT * FROM bd_comunic.USUARIO;
SELECT * FROM bd_comunic.GRUPO;
SELECT * FROM bd_comunic.GRUPO_USUARIO;
SELECT * FROM bd_comunic.CHAMADO;
SELECT * FROM bd_comunic.ITCHAMADO;

#DESABILITA A OPÇÃO DO MYSQL DE DAR UPDATE/DELETE APENAS COM PRIMARY KEY
#SET SQL_SAFE_UPDATES = 0;